from enum import Enum


class States(Enum):
    INPUT_GAME_NAME = 1
    CHECK_RESTRICTION = 2
    CHOOSE_SEND_DATE = 3
    CHOOSE_COST_LIMIT = 4
    CHOOSE_REGISTRATION_PERIOD = 5
    END_GAME_CREATION = 6
    ADMIN_TOOL_BOARD = 7
    INPUT_GAMER_NAME = 8
    INPUT_GAMER_EMAIL = 9
    INPUT_WISH_AND_INTEREST_LIST = 10
    INPUT_LETTER_TO_SANTA = 11
    FINISH_PLAYER_INFO_ENTER = 12
    INPUT_INTERESTS_LIST = 13
    INPUT_WISH_LIST = 14
    ALL_PLAYERS_GAMES = 15
    BACK_TO_ALL_GAMES = 16
    CHANGE_GAMER_INFO = 17
    REPLACE_GAMER_INFO = 18
